### ISSUE TITLE
EventBoard & ColumnItem (aka SwimlaneItem) - Delete a to-do item

### ISSUE THREAD

**Issue by fictionalparakeets** [SarahAvery/finals#14]
Requirements

While viewing a client's event board, the user can select the horizontal ellipsis for an action menu > select 'Delete' > Receive a confirmation prompt before deletion.
Then either:

    Confirm delete - Item is deleted from the database and no longer appears on the event board
    or
    Cancel delete - Menu/Prompt closes, item remains on event board, no change to database

Proposed Solution

Create child component of each item for the menu.
Create a new component for the deletion confirmation.
Acceptance Criteria

User story:
As a user viewing a client's event page I need to be able to delete a to-do item and confirm my action

**Comment by fictionalparakeets** [comment]
## Requirements
While viewing a client's event board, the user can select the horizontal ellipsis for an action menu > select 'Delete' > Receive a confirmation prompt before deletion.
Then either:
> Confirm delete - Item is deleted from the database and no longer appears on the event board
or
> Cancel delete - Menu/Prompt closes, item remains on event board, no change to database

## Proposed Solution
Create child component of each item for the menu.
Create a new component for the deletion confirmation.


## Acceptance Criteria



User story:
As a user viewing a client's event page I need to be able to delete a to-do item and confirm my action

**Comment by SarahAvery** [comment]
Most of this is complete. 

There is currently no prompt for deletion, but I think we can deal with that later, as it should only be one extra function
